package com.wrkspot.customer.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing user information.
 * <p>
 * This class is used to persist user data to the database.
 * It includes fields for the user's ID, name, email, password, and roles.
 * </p>
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class UserInfo {

    /**
     * The unique identifier for the user.
     * <p>
     * This field is automatically generated by the database.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The name of the user.
     */
    private String name;

    /**
     * The email address of the user.
     */
    private String email;

    /**
     * The password of the user.
     * <p>
     * This field should be stored in an encrypted form for security reasons.
     * </p>
     */
    private String password;

    /**
     * The roles assigned to the user.
     * <p>
     * This field contains a comma-separated list of roles, e.g., "USER,ADMIN".
     * </p>
     */
    private String roles;

}
